openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /openapi/create/session:
    post:
      tags:
      - Bank operations
      summary: Create session
      operationId: createSession
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: uuid
  /openapi/create/request:
    post:
      tags:
      - Bank operations
      summary: Create request by account
      operationId: createRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitiBankRequestApi'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: uuid
  /openapi/create/customer:
    post:
      tags:
      - Bank operations
      summary: Create customer
      operationId: createCustomer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitiBankCustomerApi'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: uuid
  /openapi/get/request/status:
    get:
      tags:
      - Bank operations
      summary: Get request status
      operationId: requestStatus
      parameters:
      - name: sessionUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: requestUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
                enum:
                - UNKNOWN
                - CREATED
                - UNAVAILIBLE
                - INSUFFICIENT_FUNDS
                - SUCCESS
                - ERROR
  /openapi/get/cards:
    get:
      tags:
      - Bank operations
      summary: Get all cards by customer uuid
      operationId: cards
      parameters:
      - name: sessionUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: citiBankCustomerUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CitiBankCard'
  /openapi/get/accounts:
    get:
      tags:
      - Bank operations
      summary: Get all accounts by customer uuid
      operationId: accounts
      parameters:
      - name: sessionUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      - name: citiBankCustomerUuid
        in: query
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CitiBankAccount'
components:
  schemas:
    CitiBankRequestApi:
      type: object
      properties:
        sessionUuid:
          type: string
          format: uuid
        requestData:
          $ref: '#/components/schemas/CitiBankRequestData'
    CitiBankRequestData:
      type: object
      properties:
        customerFromUuid:
          type: string
          format: uuid
        customerToUuid:
          type: string
          format: uuid
        currency:
          type: string
          enum:
          - RUR
          - EUR
          - USD
        amount:
          type: number
    CitiBankCustomerApi:
      type: object
      properties:
        sessionUuid:
          type: string
          format: uuid
        customerData:
          $ref: '#/components/schemas/CitiBankCustomerData'
    CitiBankCustomerData:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        age:
          type: integer
          format: int32
        email:
          type: string
        phone:
          type: string
    CitiBankCard:
      type: object
      properties:
        cardUuid:
          type: string
          format: uuid
        exists:
          type: boolean
        cardNumber:
          type: string
        accountUuid:
          type: string
          format: uuid
    CitiBankAccount:
      type: object
      properties:
        accountUuid:
          type: string
          format: uuid
        currency:
          type: string
          enum:
          - RUR
          - EUR
          - USD
        amount:
          type: number
        card:
          $ref: '#/components/schemas/CitiBankCard'
